### ISSUE TITLE
Moderator Mode

### ISSUE THREAD

**Issue by Janvier123** [mikeyaworski/Twitch-Lurker#19]
Hi!

**Is it possible to add some kind of moderator mode?
Is it possible to set moderator mode per streamer?**

When viewing twitch in **_https://www.twitch.tv/moderator/broadcaster_** it keeps opening _**https://www.twitch.tv/broadcaster**_
It would  be nice to add a shield icon next to the start (favorite) icon, indicating you are on moderator mode, and there is no need to open the normal window

There is NO need checking if the user is mod or not, twitch will do this for you.

Thx

**Comment by mikeyaworski** [comment]
I just became aware of this use case recently and I'm addressing it in the next release. Thanks for creating an issue.

**Comment by mikeyaworski** [comment]
The next release (version 2.0.3) is in review. Once that rolls out, it should no longer open anything on moderator pages. Leave another comment if there are still issues after trying that version.

db0cd204c43c69696988472fac261156c05d964e
