### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by haer0248** [mikeyaworski/Twitch-Lurker#20]
Hi, I believe I have a serious problem; neither Firefox, Edge, nor Chrome is working for me. I am unable to use Twitch login.

https://youtu.be/U5f-E-NpJ_s

**Comment by mikeyaworski** [comment]
I'll try to help, but I need a little more information.

1. Are you building the app yourself from the code in this repository, or are you downloading the extension from the web store?
2. Could you post the background page logs for the app? Here is how to do it (screenshots to help)
    ![image](https://github.com/mikeyaworski/Twitch-Lurker/assets/10966214/5c607ade-0468-4f24-885b-fe66afb9c80c)
    ![image](https://github.com/mikeyaworski/Twitch-Lurker/assets/10966214/33f34b9a-3b5b-4247-a4ef-ef08e750b2f6)
    1. Go to "Manage Extensions" on your browser. You can probably go to the URL `chrome://extensions` and it will take you there (depending on your browser).
    2. Enable "Developer Mode".
    4. Click on "Background page".
    5. In the new window that opened, click on "Console".
    6. If there are any errors (in red), expand them and take a screenshot or copy/paste them here. Any information related to this is helpful. If there are no errors, keep this window open and try to log in again.

Thanks for including a video by the way.

**Comment by haer0248** [comment]
I'm download from web store.

Chrome/Edge
```
Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Z (chrome-extension://fkjghajhfjamfjcmdkbangbeogbagnjf/background-script-bundle.js:1:25010)
    at chrome-extension://fkjghajhfjamfjcmdkbangbeogbagnjf/background-script-bundle.js:1:26049
    at Generator.next (<anonymous>)
    at s (chrome-extension://fkjghajhfjamfjcmdkbangbeogbagnjf/background-script-bundle.js:1:10963)
```

Firefox
```
Uncaught (in promise) DOMException: String contains an invalid character
    Z moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    Q moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    s moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    promise callback*c moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    s moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    promise callback*c moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    b moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    b moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    Q moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
    <anonymous> moz-extension://334a8d8d-ccc8-4c15-896d-dbecaf8fe65d/background-script-bundle.js:1
```

**Comment by mikeyaworski** [comment]
This should be fixed in the next release. The decoding of `id_token` was incorrect.

**Comment by mikeyaworski** [comment]
Thanks for pointing this out and providing details so that I could fix it!

The next release (2.0.3) is in review and it should be fixed once that rolls out.

72fb6ff68b9a4e8e62fb850b404f3fb43edbdf8c
