### ISSUE TITLE
Add option to auto send '!lurk' in chat

### ISSUE THREAD

**Issue by DeSavanger** [mikeyaworski/Twitch-Lurker#32]
Hello,

It would be a nice and fun feature to add an option in the preferences menu that automatically sends '!lurk' in the chat when a new stream tab is opened. This command could be send after a few seconds or something.

**Comment by mikeyaworski** [comment]
I think that's too close to violating the TOS. I want to avoid bot-like behavior that would draw attention to yourself like that.
