### ISSUE TITLE
New issue with Microsoft Edge

### ISSUE THREAD

**Issue by difact** [mikeyaworski/Twitch-Lurker#7]
I have been using the Chrome Extension with Microsoft Edge and it worked perfect until a couple of days ago.

It no longer opened the streams so I decided to log out and attempt to log back in.  Now when attempting to log in, it completely closes the Edge Browser. 

Chrome and Firefox do not appear to have the issue.

No events show in the Event Viewer in Windows to indicate any crashes.

**Comment by mikeyaworski** [comment]
Wow, it really crashes the browser...

I'll look into it.

**Comment by mikeyaworski** [comment]
Okay, so Microsoft broke something in one of the recent versions. Invoking `chrome.identity.launchWebAuthFlow` causes the crash, and this is happening to all extensions. Workarounds are possible, but the code will become confusing and complex, so I'm going to hold off and see if Microsoft will patch this first.

Unfortunately, you'll need to use Firefox, another Chromium browser or an older version of Edge in the meantime.

**Comment by difact** [comment]
Yes, I have issues with Chrome opening the Tabs "muted".  It appears to make the tab unable to unmute, so I couldn't use it to swap easily between lurked streams, if I wanted to unmute a stream temporarily (I don't know if this is another bug, or if I have a setting messed up somewhere). 

I am currently utilizing Firefox for another purpose, and it creates a conflict with it opening tabs if I forget to switch the focus back to a separate window.   

I will keep an eye out, hopefully Microsoft can resolve the issue, as rolling back Edge did not seem to resolve the issue (I am sure Microsoft created a compound issue).

**Comment by mikeyaworski** [comment]
FWIW, it seems like you would need to go back to a version of Edge before October. That's the first time I've seen someone else complain about this problem.

And yes unfortunately, Chrome doesn't let you unmute tabs which an extension has muted.
If you have Twitch muted, then you can uncheck the option in the extension to mute tabs, and the streams should open muted on Twitch's end by default.

**Comment by mikeyaworski** [comment]
No longer an issue.
