### ISSUE TITLE
[FireFox] Incompatible with "Alternate Player for Twitch.tv"

### ISSUE THREAD

**Issue by DUN-Cosmos** [mikeyaworski/Twitch-Lurker#8]
When both extension are installed, Twitch-Lurker will not stop to open new tab for same live.

Since the "Alternate Player for Twitch.tv" open tab with url like this :
- moz-extension://f01c3997-68c0-4a53-8053-3f33f7580e7b/player.html?channel=******

"Alternate Player for Twitch.tv" extension page :
- https://addons.mozilla.org/en-US/firefox/addon/twitch_5/

**Comment by mikeyaworski** [comment]
Yes, this involves updating the regex in these functions:

https://github.com/mikeyaworski/Twitch-Lurker/blob/7bac53aa7e2846762df2e5fcae1a81b5464b73db/app/public/background-scripts/tabs.ts#L7-L14

https://github.com/mikeyaworski/Twitch-Lurker/blob/7bac53aa7e2846762df2e5fcae1a81b5464b73db/app/public/background-scripts/utils.ts#L4-L7

I'll see if I can update these when I have some free time.

**Comment by mikeyaworski** [comment]
I don't believe this is possible to fix since the Chrome API will not return information about tabs for other Chrome extensions.
